### PR TITLE
sync canWrite branch with v2.0.15 of arduino-esp32 library

### PR DESCRIPTION
**Pull request by craiglink**
brings code base up to v2.0.15 of the arduino-esp32 WiFi library

### CODE REVIEW

**Comment by MitchBradley** [comment]
Looks like 2.0.16 just hit the platformio package repo.  https://registry.platformio.org/tools/platformio/framework-arduinoespressif32 .  I wonder if we are out of date already?

**Comment by MitchBradley** [comment]
I don't see any changes in the WiFi library between arduinoespressif32 versions 2.0.15 and 2.0.16

**Comment by craiglink** [comment]
Same here. Looks like only a 8 commit difference between the 2. We should update platformio.ini to use 2.0.16 as the is a bug in 2.0.15 caused by a back port from the 3.0 pre-release

Not sure if it would affect fluidnc's codebase, but would be the safe thing to do

**Comment by MitchBradley** [comment]
Already done https://github.com/bdring/FluidNC/pull/1207

**Pull request closed without merging**
